# Generated by Django 4.0.3 on 2022-04-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('ISBN', models.CharField(blank=True, max_length=255, null=True, verbose_name='ISMB')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('author', models.CharField(max_length=255, verbose_name='Author')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price1')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
