# Generated by Django 4.0.3 on 2022-07-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_book_author_alter_book_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='book',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='School'),
        ),
        migrations.AddField(
            model_name='dispense',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='dispense',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='dispense',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='School'),
        ),
    ]
