# Generated by Django 4.0.3 on 2022-07-04 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_book_course_book_school_dispense_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispense',
            name='allowed_user',
            field=models.ManyToManyField(null=True, related_name='bought_dispenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispense',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
