# Generated by Django 4.0.3 on 2022-07-08 15:53

import apps.products.models
import apps.products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_dispense_allowed_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispense',
            name='trial_dispense',
            field=models.FileField(null=True, upload_to=apps.products.models.dispense_trial_location),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='dispense',
            field=models.FileField(upload_to=apps.products.models.dispense_location, validators=[apps.products.validators.validate_dispense_extension]),
        ),
    ]
