version: "3.9"

services:
  django:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    depends_on:
      - postgres

  postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    env_file:
      - ./.envs/.local/.postgres

volumes: 
  db_data: