version: "3.3"

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.prod/.django
      - ./.envs/.prod/.postgres
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    ports: 
      - "5432:5432"
    env_file:
      - ./.envs/.local/.postgres
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - django

volumes: 
  local_postgres_data: {}
  local_postgres_data_backups: {}