version: "3.3"

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/front-end/static
    expose:
      - 8000
    env_file:
      - ./.envs/.prod/.django
      - ./.envs/.prod/.postgres
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/backups
    ports: 
      - "5432:5432"
    env_file:
      - ./.envs/.prod/.postgres
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/front-end/static
    ports:
      - 1337:80
    depends_on:
      - django

volumes: 
  postgres_data: {}
  postgres_data_backups: {}
  static_volume: {}