# Generated by Django 4.0.3 on 2023-04-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure_hunt', '0002_alter_treasurehuntgame_time_ended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurehuntgame',
            name='time_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treasurehuntgame',
            name='time_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
