# Generated by Django 4.0.3 on 2023-04-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure_hunt', '0003_alter_treasurehuntgame_time_ended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurehuntgame',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
