# Generated by Django 4.0.3 on 2023-04-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure_hunt', '0004_treasurehuntgame_is_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptreasure',
            name='found_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grouptreasurehint',
            name='activate_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
