# Generated by Django 4.0.3 on 2023-04-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure_hunt', '0005_grouptreasure_found_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptreasurehint',
            name='is_activate',
        ),
        migrations.AddField(
            model_name='grouptreasurehint',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not activate'), (1, 'Processing'), (2, 'Activate')], default=0),
        ),
    ]
