# Generated by Django 4.0.3 on 2022-04-04 22:11

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="used for image 'alt' attribute and SEO", max_length=255, null=True, verbose_name='title')),
                ('file', models.ImageField(blank=True, height_field='height', null=True, upload_to=apps.core.models.get_upload_to, verbose_name='file', width_field='width')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
            ],
        ),
    ]
