# Generated by Django 4.0.3 on 2022-06-30 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_abstractimage_uploaded_by_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbstractImage',
        ),
    ]
