# Generated by Django 4.0.3 on 2023-04-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='percentage_male',
            field=models.FloatField(null=True),
        ),
    ]
