# Generated by Django 4.0.3 on 2023-04-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_pokemon_height_g_pokemon_weight_g_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='base_egg_steps',
            field=models.PositiveIntegerField(),
        ),
    ]
