# Generated by Django 4.0.3 on 2023-04-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_pokemon_base_egg_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='height_cm',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weight_g',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
