# Generated by Django 4.0.3 on 2024-06-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_marker_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marker',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
