# Generated by Django 4.0.3 on 2024-06-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_marker_lat_marker_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
