# Generated by Django 4.0.3 on 2023-01-12 20:25

import apps.article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to=apps.article.models.cover_location),
        ),
    ]
