# Generated by Django 4.0.3 on 2023-11-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_cover_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url_name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
