# Generated by Django 4.0.3 on 2024-06-25 14:01

import apps.article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_articlecategory_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=apps.article.models.pdf_location),
        ),
    ]
